### ISSUE TITLE
[WARNING ] could not open file '/etc/apt/sources.list'

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/apt-formula#19]
Hello,

I'm using this formula to manage my apt repositories, I only include `apt.repositories` in my states, and my pillar looks like

```
{% set oscodename = grains['oscodename'] %}

apt:
  remove_sources_list: true
  clean_sources_list_d: true

  remove_preferences: true
  clean_preferences_d: true

  repositories:
    {{ oscodename }}:
      distro: {{ oscodename }}
      url: http://ftp.debian.org/debian
      comps: [main, contrib, non-free]
      type: [binary]
[...]
```

When I run a highstate or only the apt.repositories state, I got this error

```
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://apt/repositories.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://apt/map.jinja'
[INFO    ] Running state [debian-archive-keyring] at time 15:26:43.653378
[INFO    ] Executing state pkg.installed for debian-archive-keyring
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/root'
[INFO    ] Package debian-archive-keyring is already installed.
[INFO    ] Completed state [debian-archive-keyring] at time 15:26:43.866063
[INFO    ] Running state [/etc/apt/sources.list] at time 15:26:43.868531
[INFO    ] Executing state file.absent for /etc/apt/sources.list
[INFO    ] File /etc/apt/sources.list is not present
[INFO    ] Completed state [/etc/apt/sources.list] at time 15:26:43.870025
[INFO    ] Running state [/etc/apt/sources.list.d] at time 15:26:43.870463
[INFO    ] Executing state file.directory for /etc/apt/sources.list.d
[INFO    ] {'removed': ['/etc/apt/sources.list.d/wheezy-binary.list']}
[INFO    ] Completed state [/etc/apt/sources.list.d] at time 15:26:43.872370
[INFO    ] Running state [deb  http://ftp.debian.org/debian wheezy main contrib non-free] at time 15:26:43.873656
[INFO    ] Executing state pkgrepo.managed for deb  http://ftp.fr.debian.org/debian wheezy main contrib non-free
[WARNING ] could not open file '/etc/apt/sources.list'

[WARNING ] could not open file '/etc/apt/sources.list'

[INFO    ] Executing command 'apt-get -q update' in directory '/root'
[WARNING ] could not open file '/etc/apt/sources.list'
[...]
```

The error/warning (could not open file '/etc/apt/sources.list') appears several times, at least twice for each apt repository.

Do you have any idea of what can be the reason for this warning?

**Comment by jerrykan** [comment]
I just noticed this warning as well. Digging into it a little it appears to be coming from a call that salt is making to `aptsources.sourceslist.SourcesList()`:

  https://github.com/saltstack/salt/blob/721e6dcce87afef13b47cbbd419bf22fc2d5c0bd/salt/modules/aptpkg.py#L1414

`aptsources` is provided by the Debian package `python-apt`. The following stack traces show the exact location in `aptsources`

>   [/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py(1415)list_repos()](https://github.com/saltstack/salt/blob/721e6dcce87afef13b47cbbd419bf22fc2d5c0bd/salt/modules/aptpkg.py#L1414)
> -> sources = sourceslist.SourcesList()
>   [/usr/lib/python2.7/dist-packages/aptsources/sourceslist.py(276)__init__()](https://anonscm.debian.org/git/apt/python-apt.git/tree/aptsources/sourceslist.py?h=0.9.3.12#n276)
> -> self.refresh()
>   [/usr/lib/python2.7/dist-packages/aptsources/sourceslist.py(283)refresh()](https://anonscm.debian.org/git/apt/python-apt.git/tree/aptsources/sourceslist.py?h=0.9.3.12#n283)
> -> self.load(file)
>   [/usr/lib/python2.7/dist-packages/aptsources/sourceslist.py(394)load()](https://anonscm.debian.org/git/apt/python-apt.git/tree/aptsources/sourceslist.py?h=0.9.3.12#n394)
> -> logging.warning("could not open file '%s'\n" % file)

So this is occurs when `remove_sources_list: true` is in the pillar data, causing the `/etc/apt/sources.list` file to be removed, that then results in a warning from `aptsources` which is then passed back up through salt to the user. This is only a warning and everything seems to work as it should. This isn't necessarily a problem with salt, or this formula, but an underlying system python library.

One potential work-around would be to change the [`/etc/apt/sources.list`](https://github.com/saltstack-formulas/apt-formula/blob/4a26e31ed5fa7ba713a6d3bd28399357efd96db9/apt/repositories.sls#L12) state to ensure the file exists but is empty, instead of removing the file.

It may be worth reporting the issue upstream with salt to see if they care to implement a general work-around to suppress the warning (or they could report it upstream with the `python-apt`/`aptsources` package maintainers).
